[tox]
envlist = format, test
requires = tox-uv
runner = uv-venv-lock-runner

[testenv:format]
description = Format and lint code with ruff
skip_install = true
deps = ruff
commands =
    ruff format ksell app
    ruff check --fix ksell app

[testenv:test]
description = Run all tests with coverage
deps =
    pytest-cov
commands =
    pytest tests/ --ignore=tests/integration --cov=ksell --cov-report=xml --cov-report=term